appName: andrei-backend # This value was modified by the initial-setup python script

deployment:
  image:
    repository: templier2/andrei-backend # This value was modified by the initial-setup python script