name: 04-Destroy Azure infrastructure

on:
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout and actions/pull

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_USE_OIDC: true

jobs:
  destroy-k8s-resources:
    runs-on: ubuntu-latest
    environment: TEST

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
  
    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Install terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.9.0"

    - name: Terraform init Backend
      run: terraform init -force-copy
      working-directory: terraform/azure

    - name: Terraform apply actual infrastructure
      run: terraform destroy -auto-approve
      working-directory: terraform/azure